# Generated by Django 5.2.6 on 2025-09-30 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('people', models.IntegerField(default=1)),
                ('requested_time', models.DateTimeField()),
                ('phone', models.CharField(max_length=20)),
                ('source', models.CharField(max_length=50)),
                ('idempotency_key', models.CharField(max_length=100, unique=True)),
            ],
        ),
    ]
