# Generated by Django 5.2.6 on 2025-10-02 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_remove_managernotification_reservation_and_more'),
        ('sklad', '0003_reservation_created_by_reservation_flagged_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='client',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='timeslot',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='venue',
        ),
        migrations.AlterUniqueTogether(
            name='timeslot',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='timeslot',
            name='venue',
        ),
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.DeleteModel(
            name='Reservation',
        ),
        migrations.DeleteModel(
            name='TimeSlot',
        ),
        migrations.DeleteModel(
            name='Venue',
        ),
    ]
