# Generated by Django 5.2.6 on 2025-10-02 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='phone',
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Админ'), ('manager', 'Менеджер')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
